### PR TITLE
fixed \n next to SELECT causing error

### LINKED ISSUE #57: SELECT\n in query causes Mariaex to fail
** (exit) exited in: GenServer.call(#PID<0.269.0>, {:query, "SELECT\n  a, b\nFROM\n  test\nWHERE\n  id = 1", [], [timeout: 5000]}, 5000)
         ** (EXIT) an exception was raised:
             ** (CaseClauseError) no case clause matching: :query_send
                 (mariaex) lib/mariaex/protocol.ex:55: Mariaex.Protocol.dispatch/2
                 (mariaex) lib/mariaex/connection.ex:219: Mariaex.Connection.process/2
                 (mariaex) lib/mariaex/connection.ex:192: Mariaex.Connection.handle_info/2
                 (stdlib) gen_server.erl:593: :gen_server.try_dispatch/4
                 (stdlib) gen_server.erl:659: :gen_server.handle_msg/5
                 (stdlib) proc_lib.erl:237: :proc_lib.init_p_do_apply/3

### PR DESCRIPTION
**Pull request by chvanikoff**
Fixes #57

### CODE REVIEW

File: lib/mariaex/connection.ex [hunk 1]
```diff
@@ -208,7 +208,9 @@ defmodule Mariaex.Connection do
   end
 
   defp command({:query, statement, params, _opts}, s) do
-    Protocol.send_query(statement, params, s)
+    statement
```
Comment (liveforeverx) [inline lib/mariaex/connection.ex]: It would not be the right place to do it. Traversing of the whole string can have performance impact.

Comment (liveforeverx) [inline lib/mariaex/connection.ex]: Best place for fixing it, would be:

  defp get_command(statement) when is_binary(statement) do
    statement |> String.split(" ", parts: 2) |> hd |> String.downcase |> String.to_atom
  end

Replace `String.split` to `:binary.split([" ", "\n"])`

**Comment by liveforeverx** [comment]
Thanks!
